server:
  port: 8080


spring:
  messages:
    basename: message/msg
  datasource:
    username: group2
    password: xianglongshibazhang666
    url: jdbc:mysql://47.98.183.4/group2_gjj?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
#  thymeleaf:
#    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
#    mode: HTML5
#    #编码 可不用配置
#    encoding: UTF-8
#    #开发配置为false,避免修改模板还要重启服务器
#    cache: false
#    #配置模板路径，默认是templates，可以不用配置
#    prefix: classpath:/templates/
#    servlet:
#      #内容类别,可不用配置
#      content-type: text/html
#    suffix: .html
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  #redis
  redis:
    host: 192.168.8.132
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  main:
    allow-bean-definition-overriding: true